---

- name: "Create an avchecker user in postgres"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_user:
    name: "{{ avchecker_user }}"
  environment: '{{ item.value }}'
  run_once: true
  loop: "{{ avchecker_defaults | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: 'item.value.PGTARGETSESSIONATTRS | default("") == "read-write"'

- name: "Create the avchecker database"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_db:
    name: "{{ dbname }}"
    owner: "{% if dbname != 'postgres' %}{{ username }}{% else %}postgres{% endif %}"
  environment: '{{ item.value }}'
  run_once: true
  loop: "{{ avchecker_defaults | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  vars:
    dbname: '{{ item.value.PGDATABASE | default(username) }}'
    username: '{{ item.value.PGUSER | default(avchecker_user) }}'
  when:
    - 'item.value.PGTARGETSESSIONATTRS | default("") == "read-write"'

- name: Grant permissions
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    roles: "{{ username }}"
    privs: all
    type: schema
    objs: public
    state: present
    login_db: '{{ dbname }}'
  environment: '{{ item.value }}'
  run_once: true
  loop: "{{ avchecker_defaults | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  vars:
    dbname: '{{ item.value.PGDATABASE | default(username) }}'
    username: '{{ item.value.PGUSER | default(avchecker_user) }}'
  when: 'item.value.PGTARGETSESSIONATTRS | default("") == "read-write"'
